# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['id'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
