# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-08-21 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0002_auto_20160706_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='continuoustrace',
            unique_together=set([('file', 'pos', 'network', 'station', 'location', 'channel', 'timerange')]),
        ),
    ]
