# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-01-31 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveforms', '0002_auto_20160706_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='network',
            field=models.CharField(db_index=True, help_text='Use a single asterisk/star (*) to affect all station codes. Use a single asterisk/star in both fields, to restrict all network/station code combinations.', max_length=2),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='station',
            field=models.CharField(db_index=True, help_text='Use a single asterisk/star (*) to affect all station codes. Use a single asterisk/star in both fields, to restrict all network/station code combinations.', max_length=5),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='users',
            field=models.ManyToManyField(db_index=True, help_text='The restriction defined by network/station code above will apply to all users that are not added here.', to=settings.AUTH_USER_MODEL),
        ),
    ]
